// Code generated by `ensure mocks generate`. DO NOT EDIT.
// Source: github.com/JosiahWitt/lambgo/internal/builder (interfaces: LambdaBuilderAPI)

// Package mock_builder is a generated GoMock package.
package mock_builder

import (
	"github.com/JosiahWitt/lambgo/internal/lambgofile"
	"github.com/golang/mock/gomock"
	"reflect"
)

// MockLambdaBuilderAPI is a mock of the LambdaBuilderAPI interface in github.com/JosiahWitt/lambgo/internal/builder.
type MockLambdaBuilderAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLambdaBuilderAPIMockRecorder
}

// MockLambdaBuilderAPIMockRecorder is the mock recorder for MockLambdaBuilderAPI.
type MockLambdaBuilderAPIMockRecorder struct {
	mock *MockLambdaBuilderAPI
}

// NewMockLambdaBuilderAPI creates a new mock instance.
func NewMockLambdaBuilderAPI(ctrl *gomock.Controller) *MockLambdaBuilderAPI {
	mock := &MockLambdaBuilderAPI{ctrl: ctrl}
	mock.recorder = &MockLambdaBuilderAPIMockRecorder{mock}
	return mock
}

// NEW creates a MockLambdaBuilderAPI. This method is used internally by ensure.
func (*MockLambdaBuilderAPI) NEW(ctrl *gomock.Controller) *MockLambdaBuilderAPI {
	return NewMockLambdaBuilderAPI(ctrl)
}

// EXPECT returns a struct that allows setting up expectations.
func (m *MockLambdaBuilderAPI) EXPECT() *MockLambdaBuilderAPIMockRecorder {
	return m.recorder
}

// BuildBinaries mocks BuildBinaries on LambdaBuilderAPI.
func (m *MockLambdaBuilderAPI) BuildBinaries(_config *lambgofile.Config) error {
	m.ctrl.T.Helper()
	inputs := []interface{}{_config}
	ret := m.ctrl.Call(m, "BuildBinaries", inputs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildBinaries sets up expectations for calls to BuildBinaries.
// Calling this method multiple times allows expecting multiple calls to BuildBinaries with a variety of parameters.
//
// Inputs:
//
//	config *lambgofile.Config
//
// Outputs:
//
//	error
func (mr *MockLambdaBuilderAPIMockRecorder) BuildBinaries(_config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	inputs := []interface{}{_config}
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBinaries", reflect.TypeOf((*MockLambdaBuilderAPI)(nil).BuildBinaries), inputs...)
}
