// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/JosiahWitt/lambgo/internal/builder (interfaces: LambdaBuilderAPI)

// Package mock_builder is a generated GoMock package.
package mock_builder

import (
	reflect "reflect"

	lambgofile "github.com/JosiahWitt/lambgo/internal/lambgofile"
	gomock "github.com/golang/mock/gomock"
)

// MockLambdaBuilderAPI is a mock of LambdaBuilderAPI interface.
type MockLambdaBuilderAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLambdaBuilderAPIMockRecorder
}

// MockLambdaBuilderAPIMockRecorder is the mock recorder for MockLambdaBuilderAPI.
type MockLambdaBuilderAPIMockRecorder struct {
	mock *MockLambdaBuilderAPI
}

// NewMockLambdaBuilderAPI creates a new mock instance.
func NewMockLambdaBuilderAPI(ctrl *gomock.Controller) *MockLambdaBuilderAPI {
	mock := &MockLambdaBuilderAPI{ctrl: ctrl}
	mock.recorder = &MockLambdaBuilderAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLambdaBuilderAPI) EXPECT() *MockLambdaBuilderAPIMockRecorder {
	return m.recorder
}

// BuildBinaries mocks base method.
func (m *MockLambdaBuilderAPI) BuildBinaries(arg0 *lambgofile.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildBinaries", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildBinaries indicates an expected call of BuildBinaries.
func (mr *MockLambdaBuilderAPIMockRecorder) BuildBinaries(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildBinaries", reflect.TypeOf((*MockLambdaBuilderAPI)(nil).BuildBinaries), arg0)
}

// NEW creates a MockLambdaBuilderAPI.
func (*MockLambdaBuilderAPI) NEW(ctrl *gomock.Controller) *MockLambdaBuilderAPI {
	return NewMockLambdaBuilderAPI(ctrl)
}
