version: "2"

linters:
  default: all
  disable:
    - prealloc
    - wsl
    - nlreturn
    - wrapcheck
    - godox
    - exhaustruct
    - varnamelen
    - depguard
    - noctx
    - noinlineerr
    - paralleltest
    - revive
    - wsl_v5

  settings:
    lll:
      line-length: 160

    gocritic:
      disabled-checks:
        - ifElseChain

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives

    rules:
      # Exclude some linters from tests
      - path: _test\.go
        linters:
          - funlen
          - lll
          - goconst
          - err113
          - dupl
          - paralleltest
          - gocognit
          - maintidx
          - gosec
          - errcheck

      # Exclude some linters from mocks
      - text: mock_
        linters:
          - nosnakecase
