// Code generated by `ensure mocks generate`. DO NOT EDIT.
// Source: github.com/JosiahWitt/lambgo/internal/runcmd (interfaces: RunnerAPI)

// Package mock_runcmd is a generated GoMock package.
package mock_runcmd

import (
	"github.com/JosiahWitt/lambgo/internal/runcmd"
	"github.com/golang/mock/gomock"
	"reflect"
)

// MockRunnerAPI is a mock of the RunnerAPI interface in github.com/JosiahWitt/lambgo/internal/runcmd.
type MockRunnerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerAPIMockRecorder
}

// MockRunnerAPIMockRecorder is the mock recorder for MockRunnerAPI.
type MockRunnerAPIMockRecorder struct {
	mock *MockRunnerAPI
}

// NewMockRunnerAPI creates a new mock instance.
func NewMockRunnerAPI(ctrl *gomock.Controller) *MockRunnerAPI {
	mock := &MockRunnerAPI{ctrl: ctrl}
	mock.recorder = &MockRunnerAPIMockRecorder{mock}
	return mock
}

// NEW creates a MockRunnerAPI. This method is used internally by ensure.
func (*MockRunnerAPI) NEW(ctrl *gomock.Controller) *MockRunnerAPI {
	return NewMockRunnerAPI(ctrl)
}

// EXPECT returns a struct that allows setting up expectations.
func (m *MockRunnerAPI) EXPECT() *MockRunnerAPIMockRecorder {
	return m.recorder
}

// Exec mocks Exec on RunnerAPI.
func (m *MockRunnerAPI) Exec(_arg0 *runcmd.ExecParams) (string, error) {
	m.ctrl.T.Helper()
	inputs := []interface{}{_arg0}
	ret := m.ctrl.Call(m, "Exec", inputs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec sets up expectations for calls to Exec.
// Calling this method multiple times allows expecting multiple calls to Exec with a variety of parameters.
//
// Inputs:
//
//  *runcmd.ExecParams
//
// Outputs:
//
//  string
//  error
func (mr *MockRunnerAPIMockRecorder) Exec(_arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	inputs := []interface{}{_arg0}
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockRunnerAPI)(nil).Exec), inputs...)
}
